== Начало игры

Итак, ты начинаешь игру никому не известным слабым персонажем нулевого уровня. В процессе игры, уровень и характеристики будут расти. На начальном уровне и с каждым последующим ты будешь получать одно очко навыков (ОН), с помощью ОН ты сможешь открывать и прокачивать навыки, по одному за раз, что обеспечит тебе постепенность прогресса и возможность сделать то, что сразу может не получиться и достичь высот, о которых ты даже не мечтал!

Чтобы открыть навык - убедись, что ты находишься на экране "лист персонажа", затем - щелкни по стрелке:

!

Если навык был 0-го уровня, то он "откроется" (если 1-го и больше, то он "прокачается"). При открытии навыка ты автоматом окажешься на экране настройки, где нужно будет указать расширенные данные навыка.

На экране настройки навыка... Активируй режим редактирования.

![](https://lh3.googleusercontent.com/Ta5cghtevOZJ75kWKqEgUN_p7Ii9FyBprqNwYyvViXLG_HGdze218Mnws-ngUlvMofNhfAx9KIK4=s0)

![](https://lh3.googleusercontent.com/Ly8C3FvFIDq8QLi1a4TpND--ZItxmwLlzkT-wJNRHVk0Dwlgdo0aUTxmtY48UcxGR1ErWHFWVf0R=s0)

![](https://lh3.googleusercontent.com/GcPhAbwA4xR-T1e5elHrakO7RG3IK0O7fXApX4g08ZP8d5JwsAwcRIvydc1n1DpO1y3WnqLli8Di=s0)

Как ты понимаешь, прокачка навыка - это периодическая тренировка. Поэтому укажи периодичность повторений (ежедневно, будни, выходные, дни недели, и.т.д.):

![](https://lh3.googleusercontent.com/rd0jPggQbMhDxhdpZL7M4kKK5jAg2HlCIm9ExKqF-QAUATMSXrE6M9QsrEqxeGhN7o_pAxR3ldOP=s0)

А теперь самое интересное...

=== Прогрессия рулит

Ты помнишь, что в играх прокачка происходит постепенно? Сначала ты можешь пульнуть слабенький файербол на близкое расстояние, а позже - серию гиганских огненных шаров, испепеляющих толпы врагов. Также и в реальной жизни! Очень круто развивать свои навыки постепенно, начав с чего-то очень простого и постепенно увеличивая сложность. Прогрессия рулит!

Качки прекрасно об этом знают! Как там в тренажерке? В самом начале туда приходит чщедушный дохляк, который делает жим лежа пустого грифа штанги всего пару раз. А потом, постепенно добавляя по чуть-чуть повторы, подходы и веса - он преображается в крутого бодибилдера!

Вот и привычки/навыки мы тоже будем развивать постепенно. Помнишь, что навыки делятся на уровни от 0 до 10? Каждая задача на каждом уровне навыка будет иметь свои различные качества (сложность). Чтобы настроить постепенность, нужно определиться в чем измеряться прогресс в навыке. Например, крутость в медитации измеряется в минутах, а подтягиваний в количестве раз, пробежка - в количеств километров, а чтение - в прочитанных страницах или минутах сосредоточенного чтения.

Если крутость навыка измеряется в минутах, укажи значение, к которому ты в идеале стремишься тут:

![](https://lh3.googleusercontent.com/0VPM5p1MUJWCMzNaxMXMpBgVxCaO_qKZlN7WcekUqUEeH11qUFx0YzDPIG0VBhqolPKAbfhSYYKy=s0)

Судя по примеру выше, конечная цель - медитировать по 15 минут в день.

Если крутость навыка измеряется количеством раз (например, отжимания, подтягивания), то заполни поле "раз" необходимым числом.

!

После того, как заполнишь, нажми "сохранить" и посмотри что получится. Автоматом распределятся значения "по уровням". Начинать нужно будет с чего то простого, а потом постепенно крутеть.

![](https://lh3.googleusercontent.com/gM-VNRSz9N5-7o32atfYhAvNjBVAYSdPBOJQJ2ALeGR_IG38g4LYjdKqy8h-Wva6Pj97nPnlxTEs=s0)

Если сложность не измеряется в количестве раз или минут - используй "состояния". В зависимости от прокачки они будут меняться. Например, на уровне "ужасно" - отжимания от стены, на уровне "легендарно" - отжимания на одной руке вверх ногами!))) Вот пример такой настройки:

![](https://lh3.googleusercontent.com/L94cgT_TTtvPzEN5WRpwo6s3CZarZrnf-WiXNDS_C27pQt66LGFRi5Ro5bAFskmzERh3Np4KEkCL=s0)

![](https://lh3.googleusercontent.com/uXXTBoOwvdv57YTVkJuZWRnBhjM-OjtCuLukODehjou6mldLG2w-X6NSCv6C4PKrlJ_9cSVslw07=s0)

А что если необходимо, чтобы с каждым уровнем добавлялись новые задачи? Например, на первом уровне ты избегаешь питаться только гамбургерами, на втором - гамбургерами и фри, а на третьем - гамбургерами, фри и газировкой))):

![](https://lh3.googleusercontent.com/fSG85X_eDPdckz7LiFWBTUICXyi80vzcuC3a5nr_OGFCk9HnCG-adoDAMIaHISJV-3IGrCPFXB2o=s0)

![](https://lh3.googleusercontent.com/IFhOSQ_cMPKIsoEG_UzTrq-g4jxV0LEFw9ZrZPKnO4zm94XWjs69y4VbGkM8azAmrQ6h9f_xDJfN=s0)

Постарайся разделить на уровни каждый навык. Тут тебе поможет твоя фантазия. Можешь даже довести все до абсурда - например "чистка 1 зуба зубной нитью", "чтение 1 минута", "холодный душ - только пальцы на ногах", "одеться для пробежки и выйти на улицу, а затем вернуться домой", "вспомнить о том, что нужно сделать уборку и все" )))) Есть даже такой подход в приобретении привычек - начинать нужно с чего-то настолько элементарно простого, что было бы глупо от этого отказываться! Главное встать на путь, а сложность можно потом постепенно нарастить! (Почитай книгу Мини привычки - макси результаты.)

Вот тебе несколько примеров, для того, чтобы ты яснее представлял как настроить прогрессию...

*Чтение*

![](https://lh3.googleusercontent.com/y_7WNUjL-vDIp8xFMB1rZjwh3fxrkN5p9bTKDBAg-jjvb3YEpat75Z12vUq2jRxtvuCF4KwJueNz=s0)

*Полезная еда*

![](https://lh3.googleusercontent.com/iAQf5NsP50xkF_m29w0YfoZdDT-wEyjIJW1yc-XSKGlPgK7tQnxeZD3jKt_J_Mr5cWi2K1oek3PZ=s0)

*Сопротивление вредной еде*

![](https://lh3.googleusercontent.com/2lEYAm5KYHv5F-AMo8KJjQ3PphXnz6_Wp8kSPgjrPF-aeMNv2HtkaaiH0mztJrOWjRUZMWAS7zk7=s0)

_Примечание: есть исследования, что черный молотый кофе в малых количествах полезен, а зеленый чай для мужчин очень вреден. Поэтому в примерах чай попал во вредную еду, а кофе в полезную._

*Питье*

![](https://lh3.googleusercontent.com/eUFOxvOHJFIFwtNJc-F-Wzl7YWeD103i2GyKkbfSnGE0U7rVQv2Di0OdlregVpN5BhQ594UpE3WL=s0)

_Также следует добавить навыки "вода днем" и "вода вечером"._

*Качалка*

![](https://lh3.googleusercontent.com/UFkvCl9Ksaz0zlp4kBe6UKhXM4fmxHMoouAvlQuqJmt16fUXRRcV0_SCDysrn6dvedRJL6Owlf8P=s0)

_Тут указано количество повторений в упражнениях. Поначалу начинается с идиотского одного повтора, что очень легко, а потом постепенно идет усложнение._

*Сопротивление новостям*

![](https://lh3.googleusercontent.com/lMU7fK235-hT5B25ul1hu-PjIewZOIyC7ANPnP8HssCdOJhEnP5fRcUcHTuo3_DHd0hraz1HfUmw=s0)

*Новости это полная шляпа, и чтобы поберечь свое моральное здоровье, лучше их избегать.*

=== Посмотри задачи

Каждый открытый навык будет преобразован в конкретные действия - задачи. Чтобы посмотреть задачи на сегодня - вернись в главное окно программы:

!

А теперь... Настало время сражения! Файт!