== Файт!

![](https://lh3.googleusercontent.com/gFBuN9p36ajO2Qj114RED9lrmBiMOxirTikEQ20HGYqs7GsHMIqX_6kZjO8js88zHKvpXaXM1ArQ=s0)

Ну вот и наступил самый интересный момент - начало прокачки! 

Тут следует напомнить о цели игры.

=== Цель игры

Цель Рпг Органайзера - прокачать персонажа (и тебя тоже) до максимально возможного уровня. Максимальный уровень в игре - 100. Чтобы это сделать, нужно выполнять задачи из списка. После успешного выполнения дела ты получишь небольшую прокачку своих навыков (к которым относится задача). Когда уровень навыков будет расти, твой персонаж будет получать опыт. При достижении порогового значения опыта, будет получен новый уровень персонажа - наглядное подтверждение роста твоей крутости!))) Каждые 20 уровней твой персонаж будет получать новое звание - важный этап в твоем совершенствовании, а также новая картинка персонажа + новые картинки задач))) Честно говоря, уже к 20-му уровню ты будешь чувствовать себя совершенно другим человеком, так что желаю удачи!

=== Панель задач

Все задачи будут сконцентрированы в этом месте:

![](https://lh3.googleusercontent.com/fsRMrG0H23LN0p1l_Qe4724rpPa7JiALGMOwlbD2TPPbRH2CGfl2zZPIsxd4S8WtwbQmPxYJhEgf=s0)

Тут есть два режима отображения. Глобальный - когда ты видишь задачи списком и тут нужно выбрать первую подходящую для выполнения:

(То же, что и на примере выше)

_Внимание!!! По правильному все главное окно должно помещаться на страницу. Тоесть ты всегда внизу видишь картинку персонажа, а сверху список задач. Если задач много, то будет прокрутка ТОЛЬКО СПИСКА ЗАДАЧ. В некоторых браузерах прокручивается вся страничка, а нижняя панель интерфейса не видна. Это не правильно. Если у тебя так - обнови ХРОМ! Если после обновления не помогло - напиши мне в комментариях!_

И сфокусированный - когда ты выбрал задачу и тебе видны подробности задачи и доступны функции ее выполнения. Также над названием задачи будет случайная картинка монстра, что символизирует борьбу со сложностями и ленью. Ты победил или тебя победили... С ростом уровня персонажа монстры будут крутеть. 

![](https://lh3.googleusercontent.com/jK34SXSGyh_ALaNqT1eU_mJfhgqAYNx-Fp67tQt36iVxhLNeAOkO-cbhhPnDxo-9NheCeaim-sbh=s0)

Поначалу все задачи будут расположены "вперемешку", но не переживай, в Рпг Органайзере используется умная система сортировки задач, на следующий день порядок задач будет больше похож на ежедневный план действий.

Кроме того, все задачи делятся на два списка: навыки - повторяющиеся ежедневные задачи, выполнение которых дает опыт и качает навыки и квесты - тут будут задачи из твоих целей, их выполнение ведет к достижению целей и получению наград.

=== Панель интерфейса

Под панелью задач расположено окно интерфейса. На нем кнопки для выполнения всех необходимых действий. Тут тоже два режима:

*1) Если активирован глобальный режим задач:*

Квесты/навыки

: ![](https://lh3.googleusercontent.com/QtsAYEMMC_d6eehgnK5EvdmoM6NndG8okLlkjuOP03ZfZVZT-iCZdjBQ4sMKyX6NpAg4_sY4_Ded=s0)

: Нажимая на эти кнопки, ты можешь выбирать списки задач - квесты и навыки, соответственно.

Первая задача из списка

: ![](https://lh3.googleusercontent.com/YUUHvso70vzycixBThATLlDX7Ngb8jID0wXk6jHI3FgbVOstCBrkkBgNSPAk2gUKqWBISrJ333zu=s0)

: Нажав на эту кнопку, ты попадешь в сфокусированный режим первой задачи из списка.

*2) Если активизирован сфокусированный режим (когда выбрана конкретная задача для выполнения):*

Выполнение/пропуск

: Выполнил задачу? Молодец! Отметь это, нажав эту кнопку.

: ![](https://lh3.googleusercontent.com/okooCxGJ2xhxmdOEkFGjZlL2BfxHfNcSSPFRBIk-d7m6e_PxNZSY3Z5nfc12Ejd-Y4EXZQJSSnrF=s0)

: Поленился или не смог выполнить эту задачу? Нажми на эту кнопку и получишь небольшой штраф (в квестах эту кнопку не надо нажимать). Эта функция поможет тебе двигаться только вперед, а не останавливаться на достигнутом! Понятно, что если ты сегодня поленился и не развивал навык, твой опыт падает и ты теряешь немного крутости! Только не впадай в уныние, это не стирает твои достижения, если на следующий день ты будешь стараться!

P.S. Главное правило крутых перцев - не лажай два дня подряд! Так что если сегодня ты не смог сделать что-то - ЗАВТРА - САМЫЙ ГЛАВНЫЙ ДЕНЬ!

: ![](https://lh3.googleusercontent.com/WIoF_ufa0z8OFr5faKL3z62cHPqnFohpRO1HT9qifC2hxujt4BfaMYI0ExwcWcxKJUGJNjet8_gV=s0)

Назад в глобальный вид задач

: После того, как ты выполнил или про$@'л задачу, переход в глобальный вид переходит автоматически. Если же ты передумал сейчас делать это задачу и решил переключиться на другую - жми эту кнопку.

: ![](https://lh3.googleusercontent.com/Znh3aHhU8H4BzONQM-dDc_s5X12FufF9dB5qYYdhsFgfkzO1abe3eGUmxkJQEIcmyZjwtqofHQqt=s0)

=== В бой!

Теперь я тебе просто кратко опишу алгоритм действий в Рпг Органайзере.

=== Респаун

Ты полностью настроил все задачи, квесты, навыки, характеристики, награды... Теперь надо оповестить программу, что ты начинаешь игру. Для этого перейди в лист персонажа в режиме редактирования и в самом низу нажми кнопку "респаун":

![](https://lh3.googleusercontent.com/B4yOj-NlUoS4JfvQV9DEZ4mtyJ6uXXoQXrLknAEMyZ8SsTggfz21_wRHwwhqF2xxbOjb0wOkCe20=s0)

Даты всех задач переведутся на "сегодня" и можно будет начинать игру.

Теперь переходим в главное окно...

=== Главное окно

Сначала смотрим задачи из списка "навыки". Пробегаем глазами по всему списку и выбираем ту, которую комфортно сейчас сделать:

![](https://lh3.googleusercontent.com/9IYnBLF2v47h5BbB2lJ-yQHGl2pY7VSe0h-QQrgnbWPmOxqAXVVbN0wey8ls0rJAYXJoF2cxsfQc=s0)

Попадаем в режим фокусировки, выполняем задачу в реале и отмечаем в РПГ Органайзере:

![](https://lh3.googleusercontent.com/Zjd0f0puICGAXL2_f8lDmHcm4S6R7MUSTt2XhPFER90KxSNqgc6v3X9eijG_zsj4gWziKnCA6JXw=s0)

Далее - следующую задачу. И.т.д.

Те задачи, которые не получается сегодня сделать отмечай как "не выполненные". Когда есть желание поучаствовать в квестах - открывай список "квесты":

![](https://lh3.googleusercontent.com/cmZ756IGrhHEq6ChHVDBZwYcPGx30EMsuVtKTlNtHkqh5WSXCk4p2dgRECStRnnvR5YipR-ZY-JF=s0)

И фигачь!

Когда в одном из квестов закончатся все задания - ты попадешь на экран квестов, где нужно будет его завершить, или добавить еще заданий:

![](https://lh3.googleusercontent.com/6P5zF-O9qHitK6hl7Mf1DlzW_eCy2urjP1vvqGF6UX_5ph7OwkX42LiQYuydVvEph2wPK99gJ22H=s0)

Если при выполнении задач ты вдруг получишь награду, она появится в инвентаре:

![](https://lh3.googleusercontent.com/yD0_mc3MRghkQf6yzlsXJokrauFcFxNHBnFFW7RK-LtAMGt0rH7CVI9FsHrNf9M_pkbVhltV5SbK=s0)

Награди себя в реале и отметь это, нажав на кнопку "использовать".

![](https://lh3.googleusercontent.com/49KMu-Cc-nXDeKRZCO37BkU9Cs0TYeVDmEd4eaTAD5vuEoXDLJdf-oeenfy_UC63fv9_HJBE8yyW=s0)

Поначалу тебе будет просто набирать уровни персонажа. Задания будут проще и они будут быстрее прокачивать навыки - повышать опыт. Но со временем сложность заданий будет расти, а навыки будут повышаться медленнее. Так что достичь 100-го уровня пока еще никому не удавалось! Если ты сможешь - напиши мне и ты попадешь в [Зал Славы](http://nerdistway.blogspot.com/2013/05/blog-post_91.html)! ))) А я постараюсь быть первым (уже 40-й уровень)!)))