== Файт!

![](https://lh3.googleusercontent.com/gFBuN9p36ajO2Qj114RED9lrmBiMOxirTikEQ20HGYqs7GsHMIqX_6kZjO8js88zHKvpXaXM1ArQ=s0)

Ну вот и наступил самый интересный момент - сама ИГРА! 

=== Цель игры

Цель Рпг Органайзера - прокачать персонажа (и тебя тоже) до максимально возможного уровня. Максимальный уровень у каждого свой и он зависит от общего количества добавленных тобой навыков. Чтобы прокачивать персонажа, нужно выполнять задачи из списка. После успешного выполнения ты небольшую прибавку к очкам опыта (exp - **ex**perience **p**oints).При достижении порогового значения опыта, будет получен новый уровень персонажа - наглядное подтверждение роста твоей крутости!))) Также с новым уровнем ты получишь 1 ОН (очко навыков), на которое ты сможешь открыть или прокачать какой-либо навык персонажа (тебе станут доступны новые задания). Периодически, с ростом уровня, ты будешь получать новые звания, что символизирует прохождения важного этапа в твоем становлении героя. Прокачиваясь, очень скоро ты будешь чувствовать себя совершенно другим человеком, желаю удачи!

=== Панель задач

Все задачи будут сконцентрированы в этом месте:

![](https://lh3.googleusercontent.com/fsRMrG0H23LN0p1l_Qe4724rpPa7JiALGMOwlbD2TPPbRH2CGfl2zZPIsxd4S8WtwbQmPxYJhEgf=s0)

Тут есть два режима отображения. Глобальный - когда ты видишь задачи списком и тут нужно выбрать первую подходящую для выполнения:

(То же, что и на примере выше)

И сфокусированный - когда ты выбрал задачу и тебе видны подробности задачи и доступны функции ее выполнения. Также над названием задачи будет случайная картинка монстра, что символизирует борьбу со сложностями и ленью. Ты победил или тебя победили... С ростом уровня персонажа и/или навыков монстры будут крутеть. 

![](https://lh3.googleusercontent.com/jK34SXSGyh_ALaNqT1eU_mJfhgqAYNx-Fp67tQt36iVxhLNeAOkO-cbhhPnDxo-9NheCeaim-sbh=s0)

Все задачи делятся на два списка: навыки - повторяющиеся ежедневные задачи, выполнение которых дает опыт и качает навыки и квесты - тут будут задачи из твоих целей, их выполнение ведет к достижению целей и получению наград (про квесты мы поговорим чуть позже, тут вообще есть еще много всяких классных штук, например - награды!).

=== Панель интерфейса

Под панелью задач находится панель интерфейса. На ней кнопки для выполнения всех необходимых действий. Тут тоже два режима:

*1) Если активирован глобальный режим задач:*

Квесты/навыки

: ![](https://lh3.googleusercontent.com/QtsAYEMMC_d6eehgnK5EvdmoM6NndG8okLlkjuOP03ZfZVZT-iCZdjBQ4sMKyX6NpAg4_sY4_Ded=s0)

: Нажимая на эти кнопки, ты можешь выбирать списки задач - квесты и навыки, соответственно.

Первая задача из списка

: ![](https://lh3.googleusercontent.com/YUUHvso70vzycixBThATLlDX7Ngb8jID0wXk6jHI3FgbVOstCBrkkBgNSPAk2gUKqWBISrJ333zu=s0)

: Нажав на эту кнопку, ты попадешь в сфокусированный режим первой задачи из списка.

*2) Если активизирован сфокусированный режим (когда выбрана конкретная задача для выполнения):*

Выполнение/пропуск

: Выполнил задачу? Молодец! Отметь это, нажав эту кнопку.

: ![](https://lh3.googleusercontent.com/okooCxGJ2xhxmdOEkFGjZlL2BfxHfNcSSPFRBIk-d7m6e_PxNZSY3Z5nfc12Ejd-Y4EXZQJSSnrF=s0)

: Поленился или не смог выполнить эту задачу? Нажми на эту кнопку и получишь небольшой штраф (в квестах эту кнопку не надо нажимать). Эта функция поможет тебе двигаться только вперед, а не останавливаться на достигнутом! Понятно, что если ты сегодня поленился и не развивал навык, твой опыт падает и ты теряешь немного крутости! Только не впадай в уныние, это не стирает твои достижения, если на следующий день ты будешь стараться!

P.S. Главное правило крутых перцев - не лажай два дня подряд! Так что если сегодня ты не смог сделать что-то - ЗАВТРА - САМЫЙ ГЛАВНЫЙ ДЕНЬ!

: ![](https://lh3.googleusercontent.com/WIoF_ufa0z8OFr5faKL3z62cHPqnFohpRO1HT9qifC2hxujt4BfaMYI0ExwcWcxKJUGJNjet8_gV=s0)

Назад в глобальный вид задач

: После того, как ты выполнил или про$@'л задачу, переход в глобальный вид переходит автоматически. Если же ты передумал сейчас делать это задачу и решил переключиться на другую - жми эту кнопку.

: ![](https://lh3.googleusercontent.com/Znh3aHhU8H4BzONQM-dDc_s5X12FufF9dB5qYYdhsFgfkzO1abe3eGUmxkJQEIcmyZjwtqofHQqt=s0)

=== Жесты

Если ты пользуешься прогой на телефоне - в сфокусированном режиме на картинке монстра тебе доступны некоторые жесты:

* **Свайп влево/вправо** - предыдущая, слудующая в списке задача
* **Свайп вверх/вниз** - выполнить, провалить задачу

Теперь я тебе просто кратко опишу алгоритм действий в Рпг Органайзере.

=== Твои действия

Убедись, что выбран вид задач "навыки", и в панели задач присутствуют задачи:

!

Жестами вправо/влево, или перейдя в режим "глобальный вид" выбери подходящую для выполнения задачу:

![](https://lh3.googleusercontent.com/9IYnBLF2v47h5BbB2lJ-yQHGl2pY7VSe0h-QQrgnbWPmOxqAXVVbN0wey8ls0rJAYXJoF2cxsfQc=s0)

Попадаем в режим фокусировки, выполняем задачу в реале и отмечаем в РПГ Органайзере:

![](https://lh3.googleusercontent.com/Zjd0f0puICGAXL2_f8lDmHcm4S6R7MUSTt2XhPFER90KxSNqgc6v3X9eijG_zsj4gWziKnCA6JXw=s0)

Далее - следующую задачу. И.т.д.

Те задачи, которые не получается сегодня сделать отмечай как "не выполненные". 

И фигачь!

Поначалу тебе будет просто набирать уровни персонажа. Задания будут проще и они будут быстрее прокачивать навыки - повышать опыт. Но со временем сложность заданий будет расти, а навыки будут повышаться медленнее. Так что достичь максимального уровня пока еще никому не удавалось! Если ты сможешь - напиши мне и ты попадешь в [Зал Славы](http://nerdistway.blogspot.com/2013/05/blog-post_91.html)! ))) А я постараюсь быть первым (уже 40-й уровень)!)))

=== Новый уровень!

Рано или поздно ты достигнешь нового уровня:

!

После появления этого окошка, ты автоматически перейдешь на экран персонажа, где тебе нужно будет распределить полученные ОН:

!

Если следующий уровень в навыке по сложности абсолютно такой же, как и предыдущий, он будет подсвечен зеденым цветом. Выбирай такие навыки для следующей прокачки - так будет намного легче прогрессировать!

В простейшем виде работа с РПГ Органайзером выглядит так, но есть еще дополнительные фишки, о которых ты узнаешь дальше!