== Файт!

![](https://lh3.googleusercontent.com/gFBuN9p36ajO2Qj114RED9lrmBiMOxirTikEQ20HGYqs7GsHMIqX_6kZjO8js88zHKvpXaXM1ArQ=s0)

Ну вот и наступил самый интересный момент - начало ИГРЫ! 

=== Цель

Цель Рпг Органайзера - прокачать персонажа (и тебя тоже) до максимально возможного уровня (100). Чтобы прокачивать персонажа, нужно выполнять задачи из списка. После успешного выполнения ты получаешь небольшую прибавку к очкам опыта (exp - **ex**perience **p**oints).При достижении порогового значения опыта, будет получен новый уровень персонажа - наглядное подтверждение роста твоей крутости!)) Также с новым уровнем ты получишь несколько ОН (очко навыков), на которое ты сможешь открыть или прокачать навыки (тебе станут доступны новые задания, дающие больше опыта). Прокачиваясь, очень скоро ты будешь чувствовать себя совершенно другим человеком, желаю удачи!

=== Панель задач

Все актуальные задачи будут сконцентрированы в этом месте:

![](https://lh3.googleusercontent.com/fsRMrG0H23LN0p1l_Qe4724rpPa7JiALGMOwlbD2TPPbRH2CGfl2zZPIsxd4S8WtwbQmPxYJhEgf=s0)

*Задачи делятся на два списка:* навыки - повторяющиеся ежедневные задачи, выполнение которых дает опыт и качает навыки и квесты - тут будут задачи из твоих целей, их выполнение ведет к достижению целей и получению наград.

*В отображении списков есть два режима:*

Глобальный вид:
!

ты видишь задачи списком и тут нужно выбрать первую подходящую для выполнения.

Сфокусированный вид:
![](https://lh3.googleusercontent.com/jK34SXSGyh_ALaNqT1eU_mJfhgqAYNx-Fp67tQt36iVxhLNeAOkO-cbhhPnDxo-9NheCeaim-sbh=s0)

когда ты выбрал задачу и тебе видны подробности задачи и действия над задачей. Над названием задачи будет случайная картинка монстра, что символизирует борьбу со сложностями и ленью. Ты победил или тебя победили... С ростом уровня персонажа и/или навыков монстры будут крутеть. 

=== Панель интерфейса

Под задачами находится панель интерфейса. На ней кнопки для выполнения всех необходимых действий.

*1) Если активирован глобальный режим задач:*

Квесты/навыки

: ![](https://lh3.googleusercontent.com/QtsAYEMMC_d6eehgnK5EvdmoM6NndG8okLlkjuOP03ZfZVZT-iCZdjBQ4sMKyX6NpAg4_sY4_Ded=s0)

: Нажимая на эти кнопки, ты можешь выбирать списки задач - квесты и навыки, соответственно.

Первая задача из списка

: ![](https://lh3.googleusercontent.com/YUUHvso70vzycixBThATLlDX7Ngb8jID0wXk6jHI3FgbVOstCBrkkBgNSPAk2gUKqWBISrJ333zu=s0)

: Нажав на эту кнопку, ты попадешь в сфокусированный режим первой задачи из списка.

*2) Если активизирован сфокусированный режим:*

Выполнение/пропуск

: Выполнил задачу? Молодец! Отметь это, нажав эту кнопку.

: ![](https://lh3.googleusercontent.com/okooCxGJ2xhxmdOEkFGjZlL2BfxHfNcSSPFRBIk-d7m6e_PxNZSY3Z5nfc12Ejd-Y4EXZQJSSnrF=s0)

: Поленился или не смог выполнить эту задачу? Нажми на эту кнопку и получишь небольшой штраф (в квестах эту кнопку не надо нажимать). Эта функция поможет тебе двигаться только вперед, а не останавливаться на достигнутом! Понятно, что если ты сегодня поленился и не развивал навык, твой опыт падает и ты теряешь немного крутости! Только не впадай в уныние, это не стирает твои достижения, если на следующий день ты будешь стараться!

: ![](https://lh3.googleusercontent.com/WIoF_ufa0z8OFr5faKL3z62cHPqnFohpRO1HT9qifC2hxujt4BfaMYI0ExwcWcxKJUGJNjet8_gV=s0)

Назад в глобальный вид задач

: Если же ты передумал сейчас делать это задачу и решил переключиться на другую - жми эту кнопку.

: ![](https://lh3.googleusercontent.com/Znh3aHhU8H4BzONQM-dDc_s5X12FufF9dB5qYYdhsFgfkzO1abe3eGUmxkJQEIcmyZjwtqofHQqt=s0)

Жесты

: Чтобы выбрать следующую/предыдущую задачу сделай свайп слева направо или справа налево по картинке монстра.

: Чтобы выполнить/пропустить задачу сделай свайп снизу вверх или сверху вниз по картинке монстра.

Теперь я тебе просто кратко опишу алгоритм действий в Рпг Органайзере.

=== Работа с навыками

Убедись, что выбран вид задач "навыки", и в панели задач присутствуют задачи:

!

Задачи будут "вперемешку", поэтому первым делом осортируй их. Те, что нужно выполнять вначале дня перемести выше, а те, что в конце - ниже. Для этого нажми эту кнопку:

!

Зажми на стрелочке и сдвинь задачу как тебе нужно:

!

В конце нажми сюда:

!

Теперь жестами вправо/влево, или перейдя в режим "глобальный вид" выбери подходящую для выполнения задачу:

![](https://lh3.googleusercontent.com/9IYnBLF2v47h5BbB2lJ-yQHGl2pY7VSe0h-QQrgnbWPmOxqAXVVbN0wey8ls0rJAYXJoF2cxsfQc=s0)

Попадешь в режим фокусировки, выполни задачу в реале и отметь в РПГ Органайзере:

![](https://lh3.googleusercontent.com/Zjd0f0puICGAXL2_f8lDmHcm4S6R7MUSTt2XhPFER90KxSNqgc6v3X9eijG_zsj4gWziKnCA6JXw=s0)

Далее выбери следующую задачу, а потом еще одну...

Те задачи, которые не получается сегодня сделать отмечай как "не выполненные" (значек "щит" или свайп снизу вверх). 

И фигачь!

Когда поработаешь с "навыками", переключись на список "квесты".

=== Работа с квестами

Если у тебя есть активные квесты, их задания появятся в главном окне программы. Чтобы их увидеть, активируй вид "квесты":

!

От каждого квеста сюда будет попадать первая невыполненная задача, поэтому внимательно отнесись к сортировке задач квеста.

Выполни эту задачу в реале, а затем отметь в РПГ Органайзере:

!

Если тебе нужно будет донастроить квест, ты можешь попасть в него прямо из главного окна, щелкнув по названию задачи:

!

Рано или поздно, ты выполнишь все задачи квеста. Тогда перейди на экран этого квеста и отметь, что он завершен:

!

Если за него были какие-то награды, ты их получишь.

Когда поработаешь с квестами - возвращайся к виду "навыки" и продолжай игру!

=== Новый уровень!

Поначалу тебе будет просто набирать уровни. Задания будут проще и для перехода тебе нужно будет меньше очков опыта, но со временем сложность заданий и количество очков до следующего уровня будут расти. Так что достичь максимального уровня пока еще никому не удавалось! Если ты сможешь - напиши мне и ты попадешь в [Зал Славы](http://nerdistway.blogspot.com/2013/05/blog-post_91.html)! ))) А я постараюсь быть первым!)))

Итак, рано или поздно ты достигнешь нового уровня:

!

После появления этого окошка, ты автоматически перейдешь на экран персонажа, где тебе нужно будет распределить полученные ОН. Тыкай по стрелочкам и навыки будут улучшены:

!

Если следующий уровень в навыке по сложности абсолютно такой же, как и предыдущий, он будет подсвечен зеденым цветом. Выбирай такие навыки для следующей прокачки - так будет немного легче!

После распределения, вернись в главное окно и снова отсортируй задачи (вдруг появилось что-то новое).

Как только ты достигнешь первого уровня, ты включишься в *турнир героев* и сможешь увидеть своего персонажа в турнирной таблице:

!

=== Награды

Выполняя задачи, ты можешь случайным образом получить награду. Полученная награда попадет в "инвентарь" на экране персонажа:

!

Когда будешь готов поощерить себя - награди себя в реале, а затем щелкни по награде в РПГ Органайзере:

!

Иногда ты будешь получать награды за выполнение квестов. Тогда после того, как ты отметишь, что квест "завершен", такая награда также попадет в инвентарь. А там ты уже знаешь что с ней делать!

_Ну вот собственно и все! Выполняй задачи, щедро награждай себя и продвигайся к новым уровням! Желаю удачи!_